sonata_admin:
    title: 'SymfonyESB'
    title_logo: images/logo.png
    search: false
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]


raindrop_sonata_theme:
    theme: darkly
